version: '3'
services:
    app:
        image: node:16
        environment:
            - DEBUG=app:*
        tty: true
        ports:
            - '3000:3000'
        volumes:
            - ./src:/app
        working_dir: /app
        command: sh -c 'npx tsc; npm run dev'